/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-30 12:59:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.post;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import standardpost.model.vo.StandardPost;
import java.sql.Date;
import member.model.vo.Member;

public final class postList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/post/../common/main.jsp", Long.valueOf(1693378229907L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("standardpost.model.vo.StandardPost");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("		");
 ArrayList<StandardPost> list = (ArrayList<StandardPost>)request.getAttribute("list");
				int count = list.size();
				
      out.write("\r\n");
      out.write("				<!DOCTYPE html>\r\n");
      out.write("				<html>\r\n");
      out.write("\r\n");
      out.write("				<head>\r\n");
      out.write("					<meta charset=\"UTF-8\">\r\n");
      out.write("					<title>Community</title>\r\n");
      out.write("					<script type=\"text/javascript\" src=\"/petmily/resources/js/common/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("					<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("					<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("					<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\\\r\n");
      out.write("					<script type=\"text/javascript\">\r\n");
      out.write("						$(function () {\r\n");
      out.write("							// $.ajax({\r\n");
      out.write("							// 	url: \"/petmily/\"\r\n");
      out.write("							// })\r\n");
      out.write("							const popup = document.getElementById('newPostForm');\r\n");
      out.write("							// window.onclick = e => {\r\n");
      out.write("							// 	if (e.target === popup) {\r\n");
      out.write("							// 		// console.log('clicked else where');\r\n");
      out.write("							// 		popup.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("							// 	}else{\r\n");
      out.write("							// 		console.log('clicked else where');\r\n");
      out.write("							// 		popup.style.display = 'none';\r\n");
      out.write("							// 	}\r\n");
      out.write("							// }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							$('html').click(function (e) {\r\n");
      out.write("								if ($(e.target).parents('.newPostformBox').length < 1) {\r\n");
      out.write("									console.log('팝업 외 부분이 맞습니다')\r\n");
      out.write("									//실행 이벤트 부분\r\n");
      out.write("									document.getElementById(\"newPostForm\").style.display = 'none';\r\n");
      out.write("								} else {\r\n");
      out.write("									console.log('?????')\r\n");
      out.write("								}\r\n");
      out.write("							});\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						// function openNewPostForm() {\r\n");
      out.write("						// 	document.getElementById(\"newPostForm\").style.display = \"block\";\r\n");
      out.write("						// }\r\n");
      out.write("						// function closeNewPostForm() {\r\n");
      out.write("						// 	document.getElementById(\"newPostForm\").style.display = \"none\";\r\n");
      out.write("						// }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						function openNewPostForm() {\r\n");
      out.write("							console.log(\"new post input field clicked\");\r\n");
      out.write("							document.getElementById(\"newPostForm\").style.display = \"block\";\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("					</script>\r\n");
      out.write("					<style type=\"text/css\">\r\n");
      out.write("						@media (min-width : 1050px) {\r\n");
      out.write("							.block {\r\n");
      out.write("								width: 1050px;\r\n");
      out.write("								margin: 98px auto 0 auto;\r\n");
      out.write("								word-wrap: break-word;\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						html,\r\n");
      out.write("						body {\r\n");
      out.write("							height: 100%;\r\n");
      out.write("							font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						div#main {\r\n");
      out.write("							width: 1050px;\r\n");
      out.write("							height: 100%;\r\n");
      out.write("							border: 1px solid black;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						div#top {\r\n");
      out.write("							width: 100%;\r\n");
      out.write("							height: 100px;\r\n");
      out.write("							border: 1px solid black;\r\n");
      out.write("							margin-bottm: 3px;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						div#bottom {\r\n");
      out.write("							width: 100%;\r\n");
      out.write("							margin: 10px auto;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						div#map {\r\n");
      out.write("							width: 523px;\r\n");
      out.write("							height: 67%;\r\n");
      out.write("							border: 1px solid black;\r\n");
      out.write("							float: left;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						div#info {\r\n");
      out.write("							width: 523px;\r\n");
      out.write("							height: 67%;\r\n");
      out.write("							border: 1px solid black;\r\n");
      out.write("							float: right;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						div input#newpost {\r\n");
      out.write("							width: 690px;\r\n");
      out.write("							height: 30px;\r\n");
      out.write("							font-size: 15px;\r\n");
      out.write("							background-color: #dddddd;\r\n");
      out.write("							align-items: center;\r\n");
      out.write("							border: 0;\r\n");
      out.write("							border-radius: 5px;\r\n");
      out.write("							outline: none;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						table#post {\r\n");
      out.write("							height: auto;\r\n");
      out.write("							width: 700px;\r\n");
      out.write("							border: 1px solid;\r\n");
      out.write("							border-radius: 20px;\r\n");
      out.write("							border-collapse: collapse;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						::placeholder {\r\n");
      out.write("							text-align: center;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						table tr#postmemberid {\r\n");
      out.write("							background-color: #fda90d;\r\n");
      out.write("							padding-left: 20px;\r\n");
      out.write("							margin: 0px;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						table tr td#posteditdate {\r\n");
      out.write("							text-align: left;\r\n");
      out.write("							padding-left: 20px;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						table tr td#postbuttons {\r\n");
      out.write("							float: right;\r\n");
      out.write("							position: sticky;\r\n");
      out.write("							left: 70%;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						table tr#postbottom {\r\n");
      out.write("							border-top: 1px solid black;\r\n");
      out.write("							height: 50px;\r\n");
      out.write("							display: flex;\r\n");
      out.write("							align-items: center;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						:root {\r\n");
      out.write("							--button-color: #ffffff;\r\n");
      out.write("							--button-bg-color: #fda90d;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						button {\r\n");
      out.write("							-webkit-appearance: none;\r\n");
      out.write("							-moz-appearance: none;\r\n");
      out.write("							appearance: none;\r\n");
      out.write("\r\n");
      out.write("							background: var(--button-bg-color);\r\n");
      out.write("							color: var(--button-color);\r\n");
      out.write("\r\n");
      out.write("							/* margin: 0; */\r\n");
      out.write("							padding: 0.5rem 1rem;\r\n");
      out.write("\r\n");
      out.write("							font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("							font-size: 1rem;\r\n");
      out.write("							font-weight: 400;\r\n");
      out.write("							text-align: center;\r\n");
      out.write("							text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("							border: none;\r\n");
      out.write("							border-radius: 4px;\r\n");
      out.write("\r\n");
      out.write("							display: inline-block;\r\n");
      out.write("							width: auto;\r\n");
      out.write("\r\n");
      out.write("							box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);\r\n");
      out.write("\r\n");
      out.write("							cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("							transition: 0.5s;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						button#postsubmit{\r\n");
      out.write("							position: fixed;\r\n");
      out.write("							bottom: 10px;\r\n");
      out.write("							right: 10px;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						/* The popup form - hidden by default */\r\n");
      out.write("						.new-post-form-popup {\r\n");
      out.write("							display: none;\r\n");
      out.write("							position: fixed;\r\n");
      out.write("							top: 50%;\r\n");
      out.write("							left: 50%;\r\n");
      out.write("							transform: translate(-50%, -50%);\r\n");
      out.write("							background-color: white;\r\n");
      out.write("							box-shadow: 0 19px 38px rgba(0, 0, 0, 0.30), 0 15px 12px rgba(0, 0, 0, 0.22);\r\n");
      out.write("							width: 700px;\r\n");
      out.write("							height: 500px;\r\n");
      out.write("							z-index: 9;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						/* Add styles to the form container */\r\n");
      out.write("						.form-container {\r\n");
      out.write("							max-width: 300px;\r\n");
      out.write("							padding: 10px;\r\n");
      out.write("							background-color: white;\r\n");
      out.write("						}\r\n");
      out.write("					</style>\r\n");
      out.write("				</head>\r\n");
      out.write("\r\n");
      out.write("				<body>\r\n");
      out.write("\r\n");
      out.write("					");
      out.write('\r');
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petmily</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/petmily/resources/js/main/main.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/petmily/resources/css/main/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("\r\n");
      out.write("	<header style=\"left: 0px;\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<ul class=\"navi\">\r\n");
      out.write("				<!-- style=\"top: 50px; right: 77px;\" -->\r\n");
      out.write("				<li class=\"logo\"><a href=\"/petmily/index.jsp\">Petmily</a></li>\r\n");
      out.write("				<li>\r\n");
      out.write("               <form action=\"/petmily/selectdepartment\" method=\"get\" class='formSearch' style=\"margin-right: 80px;\">\r\n");
      out.write("                  <div class='field'>\r\n");
      out.write("                     <input class='inputSearch' id='inputSearch' name='inputSearch'\r\n");
      out.write("                        required type='text'><label for='inputSearch'>\r\n");
      out.write("                        지역, 이름으로 검색 </label>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </form>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/mis?deptSeq=578\">내주변</a></li>\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/splist\" method=\"post\">커뮤니티</a></li>\r\n");
      out.write("				");
if(member == null){ 
      out.write("\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/views/member/login.jsp\">로그인</a></li>\r\n");
      out.write("				");
 }else{ 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<li\r\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px; position: absolute; top: 25px; margin-left: 20px;\">");
      out.print( member.getMemberNick() );
      out.write("님</li>\r\n");
      out.write("				<li\r\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px;\"><a\r\n");
      out.write("					href=\"/petmily/logout\"\r\n");
      out.write("					style=\"padding-top: 0px; padding-left: 0px; padding-right: 0px; padding-bottom: 0px; margin-left: 45px; position: relative; top: 12px;\">logout</a></li>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<label for=\"menuicon\" class=\"menubtn\"> <span></span> <span></span>\r\n");
      out.write("				<span></span>\r\n");
      out.write("			</label>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"menu-container\">\r\n");
      out.write("		<div class=\"sidebar\">\r\n");
      out.write("			<span class=\"area_desc\" style=\"margin-top: 25%\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					");
 if(member == null){ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 }else{ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					<li><a href=\"#\" class=\"sidebarmenu\">마이페이지</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</span><br>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"block\" align=\"center\">\r\n");
      out.write("							<div class=\"newPostformBox\">\r\n");
      out.write("								<input id=\"newpost\" type=\"text\" placeholder=\"오늘 무슨 일이 있었나요?\" onclick=\"openNewPostForm();\">\r\n");
      out.write("								<div class=\"new-post-form-popup\" id=\"newPostForm\">\r\n");
      out.write("									<!-- TEST MEMBER SEQ : NEED TO CHANGE LATER -->\r\n");
      out.write("									<form action=\"/petmily/spnewpost\" class=\"form-container\" method=\"post\">\r\n");
      out.write("										<input type=\"text\" id=\"testpostcontent\" name=\"post-content\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("										<button type=\"submit\" id=\"postsubmit\">게시글 추가</button>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<br>\r\n");
      out.write("							");
 for(StandardPost sp : list) { 
      out.write("\r\n");
      out.write("								<table id=\"post\">\r\n");
      out.write("									<tr id=\"postmemberid\">\r\n");
      out.write("										<td colspan=\"2\" style=\"height:30px; padding-left: 20px;\">\r\n");
      out.write("											<b>\r\n");
      out.write("												");
      out.print( sp.getMemberId() );
      out.write("\r\n");
      out.write("											</b>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr id=\"postcontent\" style=\"text-align: center; padding: 30px;\">\r\n");
      out.write("										<td colspan=\"2\" style=\"padding: 30px; text-align: center;\">\r\n");
      out.write("											");
      out.print( sp.getPostContent() );
      out.write("\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr id=\"postbottom\">\r\n");
      out.write("										<td id=\"posteditdate\">수정일자 &nbsp;:&nbsp; ");
      out.print( sp.getPostDate() );
      out.write("\r\n");
      out.write("										</td>\r\n");
      out.write("										<td id=\"postbuttons\"><button>수정하기</button></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<br>\r\n");
      out.write("								</table>\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("				</body>\r\n");
      out.write("\r\n");
      out.write("				</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
