/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-01 07:31:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.post;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import post.model.vo.Post;
import standardpost.model.vo.StandardPost;
import tradepost.model.vo.TradePost;
import java.sql.Date;
import member.model.vo.Member;
import member.model.vo.Member;

public final class postList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/post/../common/main.jsp", Long.valueOf(1693536174127L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("post.model.vo.Post");
    _jspx_imports_classes.add("standardpost.model.vo.StandardPost");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("tradepost.model.vo.TradePost");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("	\n");
      out.write("		");
 ArrayList<Post> list = (ArrayList<Post>)request.getAttribute("list");
				int count = list.size();
				Member m = (Member)session.getAttribute("member");
				
      out.write("\r\n");
      out.write("				<!DOCTYPE html>\r\n");
      out.write("				<html>\r\n");
      out.write("\r\n");
      out.write("				<head>\r\n");
      out.write("					<meta charset=\"UTF-8\">\r\n");
      out.write("					<title>Community</title>\r\n");
      out.write("					<script type=\"text/javascript\" src=\"/petmily/resources/js/common/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("					<link rel=\"stylesheet\" href=\"/petmily/resources/css/post/postListCSS.css\">\r\n");
      out.write("					<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("					<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("					<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("					<script type=\"text/javascript\">\r\n");
      out.write("						$(function () {\r\n");
      out.write("							const popup = document.getElementById('newPostForm');\r\n");
      out.write("\r\n");
      out.write("							$('html').click(function (e) {\r\n");
      out.write("								// If clcicked outside of new post form div\r\n");
      out.write("								if ($(e.target).parents('div.snsbuttonswrap').length < 1) {\r\n");
      out.write("									console.log(\"clicked else where\");\r\n");
      out.write("									// disable visibility of new post form\r\n");
      out.write("									document.querySelector(\"div.newPostformBox\").style.display = 'none';\r\n");
      out.write("								}\r\n");
      out.write("							});\r\n");
      out.write("						}); // DOCUMENT READY\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						function openNewPostForm() {\r\n");
      out.write("							console.log(\"clicked\");\r\n");
      out.write("							\r\n");
      out.write("							document.querySelector(\"div.newPostformBox\").style.display = \"block\";\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						function deletePost(postSeq) {\r\n");
      out.write("							// TEST DELETEPOST TODO : CHAMGE MEMBERSEQ\r\n");
      out.write("							var seq = postSeq;\r\n");
      out.write("							var path = \"/petmily/spdelete?memberseq=16&postSeq=\" + postSeq;\r\n");
      out.write("							location.href = path;\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						function clearTextArea(element) {\r\n");
      out.write("							element.value = '';\r\n");
      out.write("						}\r\n");
      out.write("					</script>\r\n");
      out.write("				</head>\r\n");
      out.write("\r\n");
      out.write("				<body>\r\n");
      out.write("\r\n");
      out.write("					");
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petmily</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/petmily/resources/js/main/main.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/petmily/resources/css/main/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("\r\n");
      out.write("	<header style=\"left: 0px;\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<ul class=\"navi\">\r\n");
      out.write("				<!-- style=\"top: 50px; right: 77px;\" -->\r\n");
      out.write("				<li class=\"logo\"><a href=\"/petmily/index.jsp\">Petmily</a></li>\r\n");
      out.write("				<li>\r\n");
      out.write("               <form action=\"/petmily/selectdepartment\" method=\"get\" class='formSearch' style=\"margin-right: 80px;\">\r\n");
      out.write("                  <div class='field'>\r\n");
      out.write("                     <input class='inputSearch' id='inputSearch' name='inputSearch'\r\n");
      out.write("                        required type='text'><label for='inputSearch'>\r\n");
      out.write("                        지역, 이름으로 검색 </label>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </form>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/selectdepttype?selecttype=9&typename=내주변\">내주변</a></li>\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/plist\" method=\"post\">커뮤니티</a></li>\r\n");
      out.write("\r\n");
      out.write("				");
if(member == null){ 
      out.write("\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/views/member/login.jsp\">로그인</a></li>\n");
      out.write("				");
 }else{ 
      out.write("\n");
      out.write("				\n");
      out.write("				<li\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px; position: absolute; top: 25px; margin-left: 20px;\">");
      out.print( member.getMemberNick() );
      out.write("님</li>\n");
      out.write("				<li\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px;\"><a\n");
      out.write("					href=\"/petmily/logout\"\n");
      out.write("					style=\"padding-top: 0px; padding-left: 0px; padding-right: 0px; padding-bottom: 0px; margin-left: 45px; position: relative; top: 12px;\">logout</a></li>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("			</ul>\n");
      out.write("			<label for=\"menuicon\" class=\"menubtn\"> <span></span> <span></span>\n");
      out.write("				<span></span>\n");
      out.write("			</label>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("	<div class=\"menu-container\">\n");
      out.write("		<div class=\"sidebar\">\n");
      out.write("			<span class=\"area_desc\" style=\"margin-top: 25%\">\n");
      out.write("				<ul>\n");
      out.write("					");
 if(member == null) { 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 }else if(member.getMemberGrade().equals("1")){ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("\r\n");
      out.write("					<li><a href=\"/petmily/views/myPage/changeMyinfo.jsp\" class=\"sidebarmenu\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 }else if(member.getMemberGrade().equals("0")){ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					<li><a href=\"#\" class=\"sidebarmenu\">마이페이지</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/adminmain\" class=\"sidebarmenu\">업체등록</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/srtd\" class=\"sidebarmenu\">업체삭제</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/memli\" class=\"sidebarmenu\">회원등급변경</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"sidebarmenu\">일반게시판관리</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"sidebarmenu\">거래게시판관리</a></li>\r\n");
      out.write("					");
 }else if(member.getMemberGrade().equals("2")){ 
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("				</ul>\n");
      out.write("			</span><br>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");

      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"block\">\r\n");
      out.write("							<div class=\"snsbuttonswrap\">\r\n");
      out.write("								<button id=\"newpost\" type=\"text\"onclick=\"openNewPostForm();\">오늘 무슨 일이 있었나요?</button>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"newPostformBox\">\r\n");
      out.write("									<div class=\"new-post-form-popup\" id=\"newPostForm\">\r\n");
      out.write("										<form action=\"/petmily/spnewpost?memberseq=16\" class=\"form-container\" method=\"post\">\r\n");
      out.write("											<textarea name=\"post-content\" id=\"post-content-textarea\" cols=\"30\" rows=\"10\" autofocus required onfocus=\"clearTextArea(this);\">tell us your story :</textarea>\r\n");
      out.write("											<button type=\"submit\" id=\"postsubmit\">게시글 추가</button>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<br><br><br>\r\n");
      out.write("\r\n");
      out.write("							");
 for(Post p : list) { 
      out.write("\r\n");
      out.write("								");
 if(p instanceof StandardPost){ 
      out.write("\r\n");
      out.write("								<div id=\"post\" style=\"width: 700px; border-radius: 10px; padding: 10px;\">\r\n");
      out.write("								<table id=\"standardpost\" style=\"width: 100%; border-collapse: collapse; border: 1px solid #fda90d;\">\r\n");
      out.write("									<tr id=\"postmemberid\" style=\"padding-left : 20px; background-color: #fda90d;\">\r\n");
      out.write("										<td style=\"text-align: left; height: 30px; padding-left: 20px; font-weight: bold; color: white;\">일반게시글</td>\r\n");
      out.write("										<td style=\"width: 180px; font-weight: bold; color: white;\">");
      out.print( p.getLastModifiedDate() );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print( p.getMemberId() );
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr id=\"postcontent\" style=\"text-align: center;\">\r\n");
      out.write("										<td colspan=\"2\" style=\"padding: 30px;\">\r\n");
      out.write("											");
      out.print( p.getPostContent() );
      out.write("\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");
 if (m.getMemberSeq()== p.getMemberSeq()){ 
      out.write("\r\n");
      out.write("									<tr id=\"postbottom\" style=\"height: 50px; align-items: center;\">\r\n");
      out.write("											<td colspan=\"2\" id=\"posteditbutton\" style=\"text-align: right; padding-right: 20px;\"><button>수정</button></td>\r\n");
      out.write("											<!-- <td id=\"postdeletebutton\" style=\"position: relative;\"> -->\r\n");
      out.write("												<!-- <button onclick=\"deletePost(");
      out.print( p.getPostSeq() );
      out.write(");\">삭제</button></td> -->\r\n");
      out.write("\r\n");
      out.write("									</tr>\r\n");
      out.write("									");
 } 
      out.write("\r\n");
      out.write("									<!-- <tr>\r\n");
      out.write("										<td></td>\r\n");
      out.write("										<td></td>\r\n");
      out.write("									</tr> -->\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("								<br>\r\n");
      out.write("								");
 } else if (p instanceof TradePost) { 
      out.write("\r\n");
      out.write("							<div>\r\n");
      out.write("								<table id=\"tradepost\">\r\n");
      out.write("									<tr id=\"postmemberid\">\r\n");
      out.write("										<td colspan=\"3\" style=\"height:30px; padding-left: 20px;\">\r\n");
      out.write("											<b>중고거래 ");
      out.print( p.getMemberId() );
      out.write("</b>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr id=\"postcontent\" style=\"text-align: center; padding: 30px;\">\r\n");
      out.write("										<td colspan=\"3\" style=\"padding: 30px; text-align: center;\">\r\n");
      out.write("											");
      out.print( p.getPostContent() );
      out.write("\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr id=\"postbottom\">\r\n");
      out.write("										<td id=\"posteditdate\">작성일자 &nbsp;:&nbsp; ");
      out.print( p.getLastModifiedDate() );
      out.write("\r\n");
      out.write("										</td>\r\n");
      out.write("										");
 if (m.getMemberSeq()== p.getMemberSeq()){ 
      out.write("\r\n");
      out.write("											<td id=\"posteditbutton\"><button>수정</button></td>\r\n");
      out.write("											<td id=\"postdeletebutton\"><button\r\n");
      out.write("													onclick=\"deletePost(");
      out.print( p.getPostSeq() );
      out.write(");\">삭제</button></td>\r\n");
      out.write("											");
 } 
      out.write("\r\n");
      out.write("									</tr>\r\n");
      out.write("									<br>\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("								");
 }} 
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("				</body>\r\n");
      out.write("\r\n");
      out.write("				</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
