/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-05 07:53:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import pet.model.vo.Pet;
import java.util.ArrayList;
import member.model.vo.Member;

public final class changeMyinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/mypage/../common/main.jsp", Long.valueOf(1693898458000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("pet.model.vo.Pet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Pet> pet = (ArrayList<Pet>) request.getAttribute("list");
if (request.getAttribute("message") != null) {
    if (request.getAttribute("message").equals("성공적으로 변경되었습니다.")) {

      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert('");
      out.print(request.getAttribute("message") );
      out.write("');\r\n");
      out.write("    </script>\r\n");
 } } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\r\n");
      out.write("<title>My Page</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/petmily/resources/js/common/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/petmily/resources/js/info/infotap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".info-content {\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	margin: 98px auto 0 auto;\r\n");
      out.write("	word-wrap: break-word;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-share {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: 95%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-detail02 {\r\n");
      out.write("	margin-top: 120px;\r\n");
      out.write("	font-family: OhsquareAir;\r\n");
      out.write("	src: url('/petmily/resources/font/OhsquareAir.woff2') format('woff2');\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs {\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs li {\r\n");
      out.write("	background: none;\r\n");
      out.write("	color: #222;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 15px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs li.current {\r\n");
      out.write("	/* background: #ededed; */\r\n");
      out.write("	color: #222;\r\n");
      out.write("	border-bottom: 3px solid hsl(30.46deg 58.9% 45.68%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab-content {\r\n");
      out.write("	display: none;\r\n");
      out.write("	/* background: #ededed; */\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab-content.current {\r\n");
      out.write("	display: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tabs {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text] {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border:1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=email] {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border:1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=time] {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 132px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* input[type=submit] {\r\n");
      out.write("	margin-top:15px;\r\n");
      out.write("	width:200px;\r\n");
      out.write("	height:35px;\r\n");
      out.write("	border-radius:30px;\r\n");
      out.write("} */\r\n");
      out.write("input[type=tel] {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select[name=type] {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form table tr textarea {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	margin-top: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".yes {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.wrapper {\r\n");
      out.write("	border: 2px solid #cfcfcf;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background-color: #fafafa;\r\n");
      out.write("	box-shadow: 2px 2px 5px 2px #cfcfcf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.wrapper form {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	display: inline-flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 펫 정보들 */\r\n");
      out.write(".pet {\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("	display: inline-grid;\r\n");
      out.write("	justify-items: center;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("	width: 210px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".pet:hover{\r\n");
      out.write("box-shadow: 0px 0px 7px black;\r\n");
      out.write("}\r\n");
      out.write(".petimg {\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	display: grid;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-top: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".petintable {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".petintr {\r\n");
      out.write("	display: table-row-group;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".petintd-radio {\r\n");
      out.write("	display: inherit;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".petin-image1 {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".petin-image2 {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("#upetName{\r\n");
      out.write("font-family: OhsquareAir;\r\n");
      out.write("}\r\n");
      out.write("#petName{\r\n");
      out.write("font-family: OhsquareAir;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pwdChange:hover {\r\n");
      out.write("	background-color:#dfdfdf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#changeSubmit:hover {\r\n");
      out.write("	background-color:#dfdfdf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	/*  function setThumbnail(event) {\r\n");
      out.write("	 var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("	 reader.onload = function(event) {\r\n");
      out.write("	 var img = document.createElement(\"img\");\r\n");
      out.write("	 img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("	 document.querySelector(\"td#image_container\").appendChild(img);\r\n");
      out.write("	 };\r\n");
      out.write("\r\n");
      out.write("	 reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("	 } \r\n");
      out.write("	 */\r\n");
      out.write("	function readImage(input) {\r\n");
      out.write("		if (input.files && input.files[0]) {\r\n");
      out.write("			const reader = new FileReader();\r\n");
      out.write("			reader.onload = function(e) {\r\n");
      out.write("				const previewImage = document.getElementById(\"preview-image\");\r\n");
      out.write("				previewImage.src = e.target.result;\r\n");
      out.write("			}\r\n");
      out.write("			reader.readAsDataURL(input.files[0]);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	 \r\n");
      out.write("\r\n");
      out.write("	const inputImage = document.getElementById(\"input-image\");\r\n");
      out.write("	inputImage.addEventListener(\"change\", function() {\r\n");
      out.write("		readImage(this);\r\n");
      out.write("	});\r\n");
      out.write("	function ureadImage(input) {\r\n");
      out.write("		if (input.files && input.files[0]) {\r\n");
      out.write("			const reader = new FileReader();\r\n");
      out.write("			reader.onload = function(e) {\r\n");
      out.write("				const upreviewImage = document.getElementById(\"upreview-image\");\r\n");
      out.write("				upreviewImage.src = e.target.result;\r\n");
      out.write("			}\r\n");
      out.write("			reader.readAsDataURL(input.files[0]);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	const uinputImage = document.getElementById(\"uinput-image\");\r\n");
      out.write("	uinputImage.addEventListener(\"change\", function() {\r\n");
      out.write("		ureadImage(this);\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/* 	window.onload = function(){\r\n");
      out.write("		var petname = document.getElementById('petName');\r\n");
      out.write("		var addpetsub = document.getElementById('addpetsub');\r\n");
      out.write("		var checkpname = /^{1,5}$/;\r\n");
      out.write("		addpetsub.disabled = true;\r\n");
      out.write("		petname.addEventListener('keyup', function(){\r\n");
      out.write("			if(checkpname.test(petname.value)){\r\n");
      out.write("			addpetsub.disabled = false;\r\n");
      out.write("			} else {\r\n");
      out.write("			addpetsub.disabled = true;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("	};\r\n");
      out.write(" */\r\n");
      out.write(" \r\n");
      out.write("	function checkinputpet () {\r\n");
      out.write("	 \r\n");
      out.write("		var petname = document.getElementById('petName');\r\n");
      out.write("		if(petname.value.length < 1){\r\n");
      out.write("			alert(\"펫이름을 입력해 주세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("			return true;\r\n");
      out.write("	}\r\n");
      out.write(" function ucheckinputpet () {\r\n");
      out.write("	 \r\n");
      out.write("		var petname = document.getElementById('upetName');\r\n");
      out.write("		if(petname.value.length < 1){\r\n");
      out.write("			alert(\"펫이름을 입력해 주세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("			return true;\r\n");
      out.write("	}\r\n");
      out.write("	function changePwd() {\r\n");
      out.write("		location.href = \"/petmily/views/mypage/changePwd.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	var petSeq = null;\r\n");
      out.write("	var petName = null;\r\n");
      out.write("	var petType = null;\r\n");
      out.write("	var petSize = null;\r\n");
      out.write("	var petImg = null;\r\n");
      out.write("	function getValue(value) {\r\n");
      out.write("		console.log(value);\r\n");
      out.write("\r\n");
      out.write("		petSeq = document.getElementById(\"UpetSeq\" + value).value;\r\n");
      out.write("		petName = document.getElementById(\"UpetName\" + value).value;\r\n");
      out.write("		petType = document.getElementById(\"UpetType\" + value).value;\r\n");
      out.write("		petSize = document.getElementById(\"UpetSize\" + value).value;\r\n");
      out.write("		petImg = document.getElementById(\"UpetImg\" + value).value;\r\n");
      out.write("\r\n");
      out.write("		document.getElementById(\"upetSeq\").value = petSeq;\r\n");
      out.write("		document.getElementById(\"upetName\").value = petName;\r\n");
      out.write("		document.getElementById(\"duImg\").value = petImg;\r\n");
      out.write("		if (petType === \"고양이\") {\r\n");
      out.write("			petType = \"0\";\r\n");
      out.write("		} else if (petType === \"강아지\") {\r\n");
      out.write("			petType = \"1\";\r\n");
      out.write("		} else {\r\n");
      out.write("			petType = \"2\";\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById('upetType1').value === petType) {\r\n");
      out.write("			$('#upetType1').prop(\"checked\", true);\r\n");
      out.write("		} else if (document.getElementById('upetType2').value === petType) {\r\n");
      out.write("			$('#upetType2').prop(\"checked\", true);\r\n");
      out.write("		} else {\r\n");
      out.write("			$('#upetType3').prop(\"checked\", true);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (document.getElementById('upetSize1').value === petSize) {\r\n");
      out.write("			$('#upetSize1').prop(\"checked\", true);\r\n");
      out.write("		} else if (document.getElementById('upetSize2').value === petSize) {\r\n");
      out.write("			$('#upetSize2').prop(\"checked\", true);\r\n");
      out.write("		} else {\r\n");
      out.write("			$('#upetSize3').prop(\"checked\", true);\r\n");
      out.write("		}\r\n");
      out.write("		$(\"#upreview-image\").attr({\r\n");
      out.write("			src : \"/petmily/resources/images/petImg/\" + petImg\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	var btn = document.getElementById(\"fixBtn\");\r\n");
      out.write("	var div = document.getElementById(\"update\");\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("		const popup = document.getElementById('update1');\r\n");
      out.write("\r\n");
      out.write("		$('html').click(function(e) {\r\n");
      out.write("			// If clcicked outside of new post form div\r\n");
      out.write("			if ($(e.target).parents('div#tab-1').length < 1) {\r\n");
      out.write("				console.log(\"clicked else where\");\r\n");
      out.write("				// disable visibility of new post form\r\n");
      out.write("				document.querySelector(\"div.update\").style.display = 'none';\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}); // DOCUMENT READY\r\n");
      out.write("\r\n");
      out.write("	function openNewPostForm() {\r\n");
      out.write("		console.log(\"clicked\");\r\n");
      out.write("\r\n");
      out.write("		document.querySelector(\"div.update\").style.display = 'block';\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\r\n");
      out.write("	var submitBtn = document.getElementById(\"changeSubmit\");\r\n");
      out.write("	var nickname = document.getElementById(\"nickname\");\r\n");
      out.write("	\r\n");
      out.write("	const unchangedNick = nickname.value;\r\n");
      out.write("	\r\n");
      out.write("	submitBtn.disabled = true;\r\n");
      out.write("	\r\n");
      out.write("	nickname.addEventListener(\"keyup\", function(){\r\n");
      out.write("		var changedNick = nickname.value;\r\n");
      out.write("		\r\n");
      out.write("		if (changedNick !== unchangedNick) {\r\n");
      out.write("			\r\n");
      out.write("			submitBtn.disabled = false;\r\n");
      out.write("			\r\n");
      out.write("		} else if (changedNick === unchangedNick) {\r\n");
      out.write("			\r\n");
      out.write("			submitBtn.disabled = true;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petmily</title>\r\n");
      out.write("<style type=\"text/css\"> \r\n");
      out.write(".dropdown {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 100%;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown > li {\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/petmily/resources/js/main/main.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function toggleDropdown() {\r\n");
      out.write("	  var dropdown = document.getElementById(\"dropdown\");\r\n");
      out.write("	  dropdown.style.display = dropdown.style.display === \"block\" ? \"none\" : \"block\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/petmily/resources/css/main/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("\r\n");
      out.write("	<header style=\"left: 0px;\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<ul class=\"navi\">\r\n");
      out.write("				<!-- style=\"top: 50px; right: 77px;\" -->\r\n");
      out.write("				<li class=\"logo\"><a href=\"/petmily/index.jsp\">Petmily</a></li>\r\n");
      out.write("				<li>\r\n");
      out.write("               <form action=\"/petmily/selectdepartment\" method=\"get\" class='formSearch' style=\"margin-right: 80px;\">\r\n");
      out.write("                  <div class='field'>\r\n");
      out.write("                     <input class='inputSearch' id='inputSearch' name='inputSearch'\r\n");
      out.write("                        required type='text'><label for='inputSearch'>\r\n");
      out.write("                        지역, 이름으로 검색 </label>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </form>\r\n");
      out.write("				</li>\r\n");
      out.write("        \r\n");
      out.write("				<li class=\"sub-link\" onclick=\"toggleDropdown()\" style=\"margin-left:150px;\"><a href=\"#\">내주변</a>\r\n");
      out.write("				<ul class=\"dropdown\" id=\"dropdown\">\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=1&typename=의료\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">의료</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=2&typename=미용\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">미용</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=3&typename=용품\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">용품</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=4&typename=위탁\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">위탁</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=6&typename=카페/식당\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">카페/식당</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=7&typename=호텔\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">호텔</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=8&typename=문화\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">문화</a></li>\r\n");
      out.write("				<li><a href=\"/petmily/selectdepttype?selecttype=5&typename=장묘\" style=\"color : hsl(30.46deg 58.9% 45.68%)\">장묘</a></li>			\r\n");
      out.write("				</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li style=\"width:15px;\"></li>\r\n");
      out.write("				");
if(member == null){ 
      out.write("\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/views/member/login.jsp\">로그인</a></li>\r\n");
      out.write("				");
 }else{ 
      out.write("\r\n");
      out.write("				<li\r\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px; position: absolute; top: 25px;\">");
      out.print( member.getMemberNick() );
      out.write("님</li>\r\n");
      out.write("				<li\r\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px;\"><a\r\n");
      out.write("					href=\"/petmily/logout\"\r\n");
      out.write("					style=\"padding-top: 0px; padding-left: 0px; padding-right: 0px; padding-bottom: 0px;  position: relative; top: 12px;\">logout</a></li>\r\n");
      out.write("					\r\n");
      out.write("			</ul>\r\n");
      out.write("			<label for=\"menuicon\" class=\"menubtn\"> <span></span> <span></span>\r\n");
      out.write("				<span></span>\r\n");
      out.write("			</label>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"menu-container\">\r\n");
      out.write("		<div class=\"sidebar\">\r\n");
      out.write("			<span class=\"area_desc\" style=\"margin-top: 25%\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					");
 if(member == null) { 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 }else if(member.getMemberGrade().equals("1")){ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					<li><a href=\"/petmily/mypet?memberSeq=");
      out.print(member.getMemberSeq());
      out.write("\" class=\"sidebarmenu\">마이페이지</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/plist?memberseq=");
      out.print( member.getMemberSeq() );
      out.write("\" method=\"post\" class=\"sidebarmenu\">커뮤니티</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/suggest?mseq=");
      out.print(member.getMemberSeq());
      out.write("\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					");
 }else if(member.getMemberGrade().equals("0")){ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					<li><a href=\"/petmily/suggestAdmin?mseq=");
      out.print(member.getMemberSeq());
      out.write("\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/plist?memberseq=");
      out.print( member.getMemberSeq() );
      out.write("\" method=\"post\" class=\"sidebarmenu\">커뮤니티</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/adminmain\" class=\"sidebarmenu\">업체등록</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/srtd\" class=\"sidebarmenu\">업체삭제</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/memli\" class=\"sidebarmenu\">회원등급변경</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/adsp\" class=\"sidebarmenu\">일반게시판관리</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/adtp\" class=\"sidebarmenu\">거래게시판관리</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/suggestAdmin?mseq=");
      out.print(member.getMemberSeq());
      out.write("\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 }else if(member.getMemberGrade().equals("2")){ 
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("			</span><br>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"info-content\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"info-detail02\">\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"tabs\">\r\n");
      out.write("				<li class=\"tab-link current\" data-tab=\"tab-1\">나의 펫 정보</li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"tab-link\" data-tab=\"tab-2\">나의 정보</li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<hr style=\"opacity: 0.5; margin: 0px;\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"tab-1\" class=\"tab-content current\">\r\n");
      out.write("				<div style=\"position: absolute; background-color: white; left: 5%;z-index:2;\">\r\n");
      out.write("					<form action=\"/petmily/peten\" method=\"post\"\r\n");
      out.write("						enctype=\"multipart/form-data\" onsubmit=\"return checkinputpet();\">\r\n");
      out.write("						<table\r\n");
      out.write("							style=\"border-radius: 12px; box-shadow: 0px 0px 7px black; font-size: 15px; \"\r\n");
      out.write("							class=\"petintable\">\r\n");
      out.write("							<tr class=\"petintr\">\r\n");
      out.write("								<td colspan=\"3\" class=\"petintd\">나의 Petmily 추가하기.</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td colspan=\"3\" id=\"tdpetName\" class=\"petintd\"><input\r\n");
      out.write("									type=\"text\" name=\"petName\" id=\"petName\" maxlength=\"4\" placeholder=\"Petmily 이름\"\r\n");
      out.write("									style=\"width: 200px; height: 30px;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr class=\"petintr\">\r\n");
      out.write("								<td colspan=\"3\" class=\"petintd\"\r\n");
      out.write("									style=\"display: flex; width: 200px;\">나의 Petmily의 종류와 크기를 설정하세요.</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr class=\"petintr\" style=\"width: 200px; display: block;\">\r\n");
      out.write("								<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("									name=\"petType\" id=\"petType\" value=\"0\" checked>고양이</td>\r\n");
      out.write("								<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("									name=\"petType\" id=\"petType\" value=\"1\">강아지</td>\r\n");
      out.write("								<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("									name=\"petType\" id=\"petType\" value=\"2\">기타\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr class=\"petintr\">\r\n");
      out.write("								<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("									name=\"petSize\" id=\"petSize\" value=\"소형\" checked>소형(10kg 미만)</td>\r\n");
      out.write("								<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("									name=\"petSize\" id=\"petSize\" value=\"중형\">중형(10~25kg 미만)</td>\r\n");
      out.write("								<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("									name=\"petSize\" id=\"petSize\" value=\"대형\">대형(25kg 이상)</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr class=\"petintr\">\r\n");
      out.write("								<td colspan=\"2\" class=\"petin-image1\"\r\n");
      out.write("									style=\"width: 200px; height: 200px;\"><img\r\n");
      out.write("									name=\"preview-image\" id=\"preview-image\"\r\n");
      out.write("									src=\"/petmily/resources/images/mainbanner/882.jpg\"\r\n");
      out.write("									style=\"width: 350px;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr style=\"display: flex; width: 200px;\">\r\n");
      out.write("								<td id=\"image_container\" class=\"petin-image2\"><input\r\n");
      out.write("									type=\"file\" id=\"input-image\" name=\"input-image\"\r\n");
      out.write("									onchange=\"readImage(this);\" style=\"width: 200px;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr class=\"petintr\">\r\n");
      out.write("								<td colspan=\"2\" style=\"width: 100px;\"><input type=\"submit\" id=\"addpetsub\"\r\n");
      out.write("									value=\"추가\" style=\"width: 80px;\"></td>\r\n");
      out.write("								<td style=\"width: 100px;\"><input type=\"reset\" value=\"모두 지우기\"\r\n");
      out.write("									style=\"width: 80px;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				");

				if (pet != null) {
				
      out.write("\r\n");
      out.write("				");

				for (Pet p : pet) {
					int i = 1;
				
      out.write("\r\n");
      out.write("				<div class=\"pet\" style=\"margin-top:10px; border-radius: 12px;  font-size: 15px; z-index=1;\">\r\n");
      out.write("					<div class=\"petimg\"\r\n");
      out.write("						style=\"width: 200px; height: 200px; display: flex; overflow: hidden; justify-content: center;\">\r\n");
      out.write("						<img src=\"/petmily/resources/images/petImg/");
      out.print(p.getPetImg());
      out.write("\"\r\n");
      out.write("							style=\"width: 350px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"petinfo\">\r\n");
      out.write("						이름:");
      out.print(p.getPetName());
      out.write("<br> 종류:");
      out.print(p.getPetType());
      out.write("<br>\r\n");
      out.write("						크기:");
      out.print(p.getPetSize());
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"updateBtn\">\r\n");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<input type=\"hidden\" name=\"UpetSeq");
      out.print(p.getPetSeq());
      out.write("\"\r\n");
      out.write("							id=\"UpetSeq");
      out.print(p.getPetSeq());
      out.write("\" value=\"");
      out.print(p.getPetSeq());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"UpetName");
      out.print(p.getPetSeq());
      out.write("\"\r\n");
      out.write("							id=\"UpetName");
      out.print(p.getPetSeq());
      out.write("\" value=\"");
      out.print(p.getPetName());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"UpetType");
      out.print(p.getPetSeq());
      out.write("\"\r\n");
      out.write("							id=\"UpetType");
      out.print(p.getPetSeq());
      out.write("\" value=\"");
      out.print(p.getPetType());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"UpetSize");
      out.print(p.getPetSeq());
      out.write("\"\r\n");
      out.write("							id=\"UpetSize");
      out.print(p.getPetSeq());
      out.write("\" value=\"");
      out.print(p.getPetSize());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"UpetImg");
      out.print(p.getPetSeq());
      out.write("\"\r\n");
      out.write("							id=\"UpetImg");
      out.print(p.getPetSeq());
      out.write("\" value=\"");
      out.print(p.getPetImg());
      out.write("\">\r\n");
      out.write("						<button id=\"fixBtn\" value=\"");
      out.print(p.getPetSeq());
      out.write("\"\r\n");
      out.write("							onclick=\"getValue(this.value);openNewPostForm();\">수정하기</button>\r\n");
      out.write("\r\n");
      out.write("						<form action=\"/petmily/petdel\" method=\"post\">\r\n");
      out.write("							<input type=\"hidden\" name=\"dmemberSeq\" id=\"deletePet\"\r\n");
      out.write("								value=\"");
      out.print(p.getMemberSeq());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("								name=\"deletePet\" id=\"deletePet\" value=\"");
      out.print(p.getPetSeq());
      out.write("\">\r\n");
      out.write("								<input type=\"hidden\" name=\"deleteImg\" id=\"deleteImg\" value=\"");
      out.print(p.getPetImg());
      out.write("\">\r\n");
      out.write("							<input type=\"submit\" value=\"삭제\">\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				}else{
				
      out.write("\r\n");
      out.write("				<h1 style=\"text-align: center;\">등록된 펫밀리가 없습니다. 좌측의 펫밀리 추가하기로 나의 펫밀리를 추가해 주세요.</h1>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("				<div class=\"update1\" id=\"update1\">\r\n");
      out.write("					<div class=\"update\" id=\"update\"\r\n");
      out.write("						style=\"position: absolute; background-color: white; left: 5%; top: 186px; z-index: 3; display: none;border-radius: 20px; width:210px;\">\r\n");
      out.write("						<form action=\"/petmily/petup\" method=\"post\"\r\n");
      out.write("							enctype=\"multipart/form-data\"onsubmit=\"return ucheckinputpet();\">\r\n");
      out.write("							<input type=\"hidden\" name=\"duImg\" id=\"duImg\">\r\n");
      out.write("							<input type=\"hidden\" name=\"memberSeq\" id=\"memberSeq\"\r\n");
      out.write("								value=\"");
      out.print(member.getMemberSeq());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("								name=\"upetSeq\" id=\"upetSeq\">\r\n");
      out.write("							<table\r\n");
      out.write("								style=\"  font-size: 15px;\"\r\n");
      out.write("								class=\"petintable\">\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td colspan=\"3\" class=\"petintd\">나의 Petmily 수정하기</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td colspan=\"3\" class=\"petintd\"><input type=\"text\"\r\n");
      out.write("										name=\"upetName\" id=\"upetName\" placeholder=\"Petmily 이름\"\r\n");
      out.write("										style=\"width: 200px; height: 30px;\" class=\"petintd\" maxlength=\"4\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td colspan=\"3\" class=\"petintd\"\r\n");
      out.write("										style=\"display: flex; width: 200px;\">나의 Petmily의 종류와 크기를 설정하세요.</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("										name=\"upetType\" id=\"upetType1\" value=\"0\">고양이</td>\r\n");
      out.write("									<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("										name=\"upetType\" id=\"upetType2\" value=\"1\">강아지</td>\r\n");
      out.write("									<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("										name=\"upetType\" id=\"upetType3\" value=\"2\">기타\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("										name=\"upetSize\" id=\"upetSize1\" value=\"소형\">소형(10kg 미만)</td>\r\n");
      out.write("									<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("										name=\"upetSize\" id=\"upetSize2\" value=\"중형\">중형(10~25kg\r\n");
      out.write("										미만)</td>\r\n");
      out.write("									<td class=\"petintd-radio\"><input type=\"radio\"\r\n");
      out.write("										name=\"upetSize\" id=\"upetSize3\" value=\"대형\">대형(25kg 이상)</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td colspan=\"2\" class=\"petin-image1\"\r\n");
      out.write("										style=\"width: 200px; height: 200px;\"><img\r\n");
      out.write("										name=\"upreview-image\" id=\"upreview-image\"\r\n");
      out.write("										src=\"/petmily/resources/images/mainbanner/882.jpg\"\r\n");
      out.write("										style=\"width: 350px;\"></td>\r\n");
      out.write("									<td id=\"image_container\" class=\"petin-image2\"><input\r\n");
      out.write("										type=\"file\" id=\"uinput-image\" name=\"uinput-image\"\r\n");
      out.write("										onchange=\"ureadImage(this);\" style=\"width: 200px;\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"petintr\">\r\n");
      out.write("									<td colspan=\"2\" style=\"width: 100px;\"><input type=\"submit\"\r\n");
      out.write("										value=\"수정완료\" style=\"width: 80px;\"></td>\r\n");
      out.write("									<td><input type=\"reset\" value=\"모두 지우기\" style=\"width: 80px;\"></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"tab-2\" class=\"tab-content\">\r\n");
      out.write("				<div class=\"wrapper\">\r\n");
      out.write("					<div style=\"text-align:center;\">\r\n");
      out.write("						<p style=\"margin-bottom:2px;\">고객님께서 가입하신 펫밀리 계정정보입니다.</p>\r\n");
      out.write("						<p style=\"font-size:15px; margin-top:3px;\">닉네임만 변경 가능합니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<form action=\"/petmily/myinfo\" method=\"post\">\r\n");
      out.write("						<table id=\"outer\" align=\"center\" width=\"500\" cellspacing=\"5\"\r\n");
      out.write("							cellpadding=\"0\">\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th width=\"140\">아이디</th>\r\n");
      out.write("								<td><input type=\"text\" name=\"userid\" value=\"");
      out.print(member.getMemberId());
      out.write("\"\r\n");
      out.write("									readonly>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th width=\"140\">이메일</th>\r\n");
      out.write("								<td><input type=\"email\" name=\"email\" value=\"");
      out.print(member.getMemberEmail());
      out.write("\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th width=\"140\">(*)닉네임</th>\r\n");
      out.write("								<td><input type=\"text\" name=\"nickname\" id=\"nickname\" value=\"");
      out.print(member.getMemberNick());
      out.write("\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<div style=\"text-align:center; margin-top:10px;\">\r\n");
      out.write("						\r\n");
      out.write("							<input type=\"button\" value=\"비밀번호 변경\" id=\"pwdChange\" onclick=\"changePwd();\" \r\n");
      out.write("							style=\"margin-bottom:15px; width:150px; height:30px; \r\n");
      out.write("							border-radius:5px; border:1px solid black;\r\n");
      out.write("							box-shadow:1px 1px 0px 1px #cfcfcf;\">\r\n");
      out.write("							&nbsp; \r\n");
      out.write("							<input type=\"submit\" value=\"변경하기\" id=\"changeSubmit\"\r\n");
      out.write("							style=\"margin-bottom:15px; width:150px; height:30px; \r\n");
      out.write("							border-radius:5px; border:1px solid black;\r\n");
      out.write("							box-shadow:1px 1px 0px 1px #cfcfcf;\">\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
