/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78

 * Generated at: 2023-08-30 07:52:37 UTC

 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.department;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import department.model.vo.Department;
import com.google.gson.Gson;
import member.model.vo.Member;

public final class deptsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/department/../common/main.jsp", Long.valueOf(1693378229907L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("department.model.vo.Department");
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

ArrayList<Department> list = (ArrayList<Department>) request.getAttribute("list");
String searhInfo = (String) request.getAttribute("search");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petmily</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/petmily/resources/js/main/banner_scroll.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@media ( min-width : 1050px) {\r\n");
      out.write("	.block {\r\n");
      out.write("		width: 1050px;\r\n");
      out.write("		margin: 98px auto 0 auto;\r\n");
      out.write("		word-wrap: break-word;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#main {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#top {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	margin-bottm: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#bottom {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#map {\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#info {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	float: right;\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1#searchvalue {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img#searchImg {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petmily</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/petmily/resources/js/main/main.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/petmily/resources/css/main/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("\r\n");
      out.write("	<header style=\"left: 0px;\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<ul class=\"navi\">\r\n");
      out.write("				<!-- style=\"top: 50px; right: 77px;\" -->\r\n");
      out.write("				<li class=\"logo\"><a href=\"/petmily/index.jsp\">Petmily</a></li>\r\n");
      out.write("				<li>\r\n");
      out.write("               <form action=\"/petmily/selectdepartment\" method=\"get\" class='formSearch' style=\"margin-right: 80px;\">\r\n");
      out.write("                  <div class='field'>\r\n");
      out.write("                     <input class='inputSearch' id='inputSearch' name='inputSearch'\r\n");
      out.write("                        required type='text'><label for='inputSearch'>\r\n");
      out.write("                        지역, 이름으로 검색 </label>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </form>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/mis?deptSeq=578\">내주변</a></li>\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/splist\" method=\"post\">커뮤니티</a></li>\r\n");

      out.write("				");
if(member == null){ 
      out.write("\r\n");
      out.write("				<li><a class=\"sub-link\" href=\"/petmily/views/member/login.jsp\">로그인</a></li>\r\n");
      out.write("				");
 }else{ 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<li\r\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px; position: absolute; top: 25px; margin-left: 20px;\">");
      out.print( member.getMemberNick() );
      out.write("님</li>\r\n");
      out.write("				<li\r\n");
      out.write("					style=\"display: inline-block; font-size: 15px; width: 90px; height: 20px;\"><a\r\n");
      out.write("					href=\"/petmily/logout\"\r\n");
      out.write("					style=\"padding-top: 0px; padding-left: 0px; padding-right: 0px; padding-bottom: 0px; margin-left: 45px; position: relative; top: 12px;\">logout</a></li>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<label for=\"menuicon\" class=\"menubtn\"> <span></span> <span></span>\r\n");
      out.write("				<span></span>\r\n");
      out.write("			</label>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"menu-container\">\r\n");
      out.write("		<div class=\"sidebar\">\r\n");
      out.write("			<span class=\"area_desc\" style=\"margin-top: 25%\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					");
 if(member == null){ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 }else{ 
      out.write("\r\n");
      out.write("					<li class=\"sidebarmenutitle\">더보기</li>\r\n");
      out.write("					<li><a href=\"#\" class=\"sidebarmenu\">마이페이지</a></li>\r\n");
      out.write("					<li><a href=\"/petmily/suggest\" class=\"sidebarmenu\">고객센터</a></li>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</span><br>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"main\" class=\"block\">\r\n");
      out.write("		<div id=\"top\">\r\n");
      out.write("			<h1 id=\"searchvalue\">\r\n");
      out.write("				검색 정보 :\r\n");
      out.write("				");
      out.print(searhInfo);
      out.write("</h1>\r\n");
      out.write("			<h3>\r\n");
      out.write("				내위치 : 위도 = <span id=\"lat\"></span>, 경도 = <span id=\"lng\"></span>\r\n");
      out.write("			</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<script type=\"text/javascript\">\r\n");
      out.write("				var lat = 0;\r\n");
      out.write("				var lng = 0;\r\n");
      out.write("\r\n");
      out.write("				//실행시 권한 요청을 수락하여야 함.\r\n");
      out.write("				navigator.geolocation.getCurrentPosition(function(position) {\r\n");
      out.write("					lat = position.coords.latitude;\r\n");
      out.write("					lng = position.coords.longitude;\r\n");
      out.write("\r\n");
      out.write("					document.getElementById(\"lat\").innerHTML = lat;\r\n");
      out.write("					document.getElementById(\"lng\").innerHTML = lng;\r\n");
      out.write("				});\r\n");
      out.write("			</script>\r\n");
      out.write("			<hr>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"bottom\">\r\n");
      out.write("			<div id=\"map\">\r\n");
      out.write("				<script type=\"text/javascript\"\r\n");
      out.write("					src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=47b2dcffee9e1b18c1d5105786e522b7\"></script>\r\n");
      out.write("				<script>\r\n");
      out.write("					var dept = ");
      out.print(new Gson().toJson(list));
      out.write(";\r\n");
      out.write("					console.log(dept);\r\n");
      out.write("\r\n");
      out.write("					if (\r\n");
      out.write("				");
      out.print(list.size());
      out.write("\r\n");
      out.write("					> 0) {\r\n");
      out.write("						lat = dept[0].deptLatitude;\r\n");
      out.write("						lng = dept[0].deptLongitude;\r\n");
      out.write("					} else {\r\n");
      out.write("\r\n");
      out.write("						lat = 33.451475;\r\n");
      out.write("						lng = 126.570528;\r\n");
      out.write("					}\r\n");
      out.write("\r\n");
      out.write("					var container = document.getElementById('map');\r\n");
      out.write("					var options = {\r\n");
      out.write("						center : new kakao.maps.LatLng(lat, lng),\r\n");
      out.write("						level : 3\r\n");
      out.write("					};\r\n");
      out.write("\r\n");
      out.write("					var imageSrc = null;\r\n");
      out.write("\r\n");
      out.write("					var map = new kakao.maps.Map(container, options);\r\n");
      out.write("					for (var i = 0; i < dept.length; i++) {\r\n");
      out.write("						var type = dept[i].deptType;\r\n");
      out.write("						if (type == 1) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/hospital.png\";\r\n");
      out.write("						} else if (type == 2) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/miyong.png\";\r\n");
      out.write("						} else if (type == 3) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/yongpom.png\";\r\n");
      out.write("						} else if (type == 4) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/wetak.png\";\r\n");
      out.write("						} else if (type == 5) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/die.png\";\r\n");
      out.write("						} else if (type == 6) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/food.png\";\r\n");
      out.write("						} else if (type == 7) {\r\n");
      out.write("							imageSrc = \"/petmily/resources/images/marker/hotel.png\";\r\n");
      out.write("						} else if (type == 8) {\r\n");
      out.write("							imageSrc = \"https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png\";\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("						var imageSize = new kakao.maps.Size(34, 45);\r\n");
      out.write("\r\n");
      out.write("						// 마커 이미지를 생성합니다    \r\n");
      out.write("						var markerImage = new kakao.maps.MarkerImage(imageSrc,\r\n");
      out.write("								imageSize);\r\n");
      out.write("\r\n");
      out.write("						var marker = new kakao.maps.Marker(\r\n");
      out.write("								{\r\n");
      out.write("									map : map,\r\n");
      out.write("									position : new kakao.maps.LatLng(\r\n");
      out.write("											dept[i].deptLatitude,\r\n");
      out.write("											dept[i].deptLongitude),\r\n");
      out.write("									title : dept[i].deptName,\r\n");
      out.write("									image : markerImage\r\n");
      out.write("								});\r\n");
      out.write("\r\n");
      out.write("						var content = '<div style=\"padding:10px;\">' + '<h4>'\r\n");
      out.write("								+ dept[i].deptName + '</h4>' + '</div>';\r\n");
      out.write("								\r\n");
      out.write("						\r\n");
      out.write("						var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("					    	position : new kakao.maps.LatLng(\r\n");
      out.write("									dept[i].deptLatitude,\r\n");
      out.write("									dept[i].deptLongitude), \r\n");
      out.write("					    	content : content\r\n");
      out.write("					    });\r\n");
      out.write("\r\n");
      out.write("						marker.setMap(map);\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					 infowindow.open(map,marker);\r\n");
      out.write("					\r\n");
      out.write("				</script>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"info\">\r\n");
      out.write("				<h2>\r\n");
      out.write("					검색 결과 :\r\n");
      out.write("					");
      out.print(list.size());
      out.write("\r\n");
      out.write("					개\r\n");
      out.write("				</h2>\r\n");
      out.write("				<hr>\r\n");
      out.write("				");

				for (Department dept : list) {
				
      out.write("\r\n");
      out.write("				<div id=\"searchInfo\">\r\n");
      out.write("					<img id=\"searchImg\"\r\n");
      out.write("						src=\"/petmily/resources/images/mainbanner/885.jpg\" align=\"left\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<a href=\"/petmily/mis?deptSeq=");
      out.print(dept.getDeptSeq());
      out.write('"');
      out.write('>');
      out.print(dept.getDeptName());
      out.write("</a>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<h4>");
      out.print(dept.getDeptAddress());
      out.write("</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<hr>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
