/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-31 12:01:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class findinfoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Petmily</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/petmily/resources/js/common/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  ");
 String message = (String) request.getAttribute("message"); 
      out.write("\r\n");
      out.write("  ");
 if (message != null && message.equals("성공메세지보냄")) { 
      out.write("\r\n");
      out.write("    <!-- 메세지 값이 \"성공메세지보냄\"인 경우 -->\r\n");
      out.write("    ");
 Member m = (Member) request.getAttribute("member"); 
      out.write("\r\n");
      out.write("    	alert(\"가입하신 아이디는 [");
      out.print( m.getMemberId() );
      out.write("] 입니다.\");\r\n");
      out.write("	  	location.href=\"/petmily/views/member/login.jsp\";\r\n");
      out.write("  ");
 } else if (message != null) { 
      out.write("\r\n");
      out.write("    <!-- 메세지 값이 \"성공메세지보냄\"이 아닌 경우 -->\r\n");
      out.write("    alert(\"");
      out.print( message );
      out.write("\");\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'Surround';\r\n");
      out.write("	src: url('/petmily/resources/font/surround.woff2') format('woff2');\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Surround', sans-serif;\r\n");
      out.write("	padding: 20px 50px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	color: hsl(30.5, 77.6%, 29.8%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body h1 a {\r\n");
      out.write("	font-family: 'Surround', sans-serif;\r\n");
      out.write("	padding: 20px 50px;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: hsl(30.46deg 58.9% 45.68%);\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body h2 {\r\n");
      out.write("	font-family: 'Surround', sans-serif;\r\n");
      out.write("	padding: 20px 50px;\r\n");
      out.write("	color: hsl(30.5, 77.6%, 29.8%);\r\n");
      out.write("	font-size: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	text-align: center; \r\n");
      out.write("	margin: 0 auto; \r\n");
      out.write("	width: 350px; \r\n");
      out.write("	height: auto;\r\n");
      out.write("	background-color: #FFE4B5;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	border: solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find-all {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	hieght: 100%;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	padding-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("	height: 33px;\r\n");
      out.write("	width: 222px;\r\n");
      out.write("	margin-top: 28px;\r\n");
      out.write("	border-radius: 13px;\r\n");
      out.write("	font-family: 'Surround', sans-serif;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"]:focus {\r\n");
      out.write("	outline: 3px solid #DAA520;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<h1 align=\"left\">\r\n");
      out.write("			<a href=\"/petmily/index.jsp\">Petmily</a>\r\n");
      out.write("		</h1>\r\n");
      out.write("	</header>\r\n");
      out.write("	<h2 align=\"center\">\r\n");
      out.write("		ID/PASSWORD 조회\r\n");
      out.write("		</h1>\r\n");
      out.write("		<div class=\"find-all\">\r\n");
      out.write("			<div class=\"find\">\r\n");
      out.write("				<form action=\"/petmily/idfind\">\r\n");
      out.write("					<ul style=\"padding: 0px;\">\r\n");
      out.write("						<li style=\"margin-top: 17px; color: black;\">아이디 찾기</li>\r\n");
      out.write("\r\n");
      out.write("						<li><input type=\"text\" name=\"memail\" placeholder=\"회원가입시 입력한 Email 입력\"\r\n");
      out.write("							required\r\n");
      out.write("							style=\"height: 33px; width: 222px; margin-top: 28px; border-radius: 13px; font-family: 'Surround', sans-serif; font-size: 16px; border: solid 3px black;\"></li>\r\n");
      out.write("						<li><input type=\"submit\" value=\"아이디 조회\"\r\n");
      out.write("							style=\"margin-top: 7px; height: 39px; border: none; background-color: #DEB887; font-family: 'Surround', sans-serif; font-size: 16px;\"></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"margin: 50px;\"></div>\r\n");
      out.write("			<div class=\"find\">\r\n");
      out.write("				<form action=\"/petmily/pwdfind\">\r\n");
      out.write("					<ul style=\"padding: 0px;\">\r\n");
      out.write("						<li style=\"margin-top: 17px; color: black;\">비밀번호 찾기</li>\r\n");
      out.write("						<li><input type=\"text\" name=\"pmid\" placeholder=\"아이디 입력\" required\r\n");
      out.write("							style=\"height: 33px; width: 222px; margin-top: 15px; border-radius: 13px; font-family: 'Surround', sans-serif; font-size: 16px; border: solid 3px;\"></li>\r\n");
      out.write("						<li><input type=\"text\" name=\"pmemail\" placeholder=\"회원가입시 입력한 Email 입력\"\r\n");
      out.write("							required\r\n");
      out.write("							style=\"height: 33px; width: 222px; margin-top: 5px; border-radius: 13px; font-family: 'Surround', sans-serif; font-size: 16px; border: solid 3px;\"></li>\r\n");
      out.write("						<li><input type=\"submit\" value=\"비밀번호 찾기\"\r\n");
      out.write("							style=\"margin-top: 7px; height: 39px; border: none; background-color: #DEB887; font-family: 'Surround', sans-serif; font-size: 16px; width: 230px; border-radius: 13px;\"></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
